# Generated by Django 2.2.7 on 2020-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('water_per_day', models.CharField(max_length=256)),
                ('diet', models.CharField(max_length=256)),
                ('no_of_meals', models.CharField(max_length=256)),
                ('first_meal_time', models.CharField(max_length=256)),
                ('last_meal_time', models.CharField(max_length=256)),
                ('same_time_meal', models.CharField(max_length=256)),
                ('do_exercise', models.CharField(max_length=256)),
                ('exercise_period', models.CharField(max_length=256)),
                ('exercise_detail', models.TextField()),
                ('sleep_period', models.CharField(max_length=256)),
                ('sleep_time', models.CharField(max_length=256)),
                ('wake_up_time', models.CharField(max_length=256)),
                ('medical_checkup', models.CharField(max_length=256)),
                ('chronic_issue', models.CharField(max_length=256)),
                ('chronic_issue_detail', models.TextField()),
                ('mental_important', models.IntegerField()),
                ('mental_effect', models.IntegerField()),
                ('stress', models.CharField(max_length=256)),
                ('stress_relief', models.TextField()),
                ('job_school_rate', models.IntegerField()),
                ('family_rate', models.IntegerField()),
                ('friends_rate', models.IntegerField()),
                ('partner_rate', models.IntegerField()),
                ('sns_rate', models.IntegerField()),
                ('money_rate', models.IntegerField()),
                ('depression', models.CharField(max_length=256)),
                ('anxiety_disorder', models.CharField(max_length=256)),
                ('bipolar_disorder', models.CharField(max_length=256)),
                ('mental_diseases', models.CharField(max_length=256)),
                ('mental_detail', models.TextField()),
            ],
            options={
                'db_table': 'surveys',
                'get_latest_by': 'created',
            },
        ),
    ]
