# Generated by Django 3.1.1 on 2020-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_auto_20200908_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg', models.IntegerField()),
                ('plas', models.IntegerField()),
                ('pres', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('insu', models.IntegerField()),
                ('mass', models.FloatField()),
                ('pedi', models.FloatField()),
                ('age', models.IntegerField()),
                ('tested', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diabetes',
                'get_latest_by': 'created',
            },
        ),
    ]
