# Generated by Django 3.1.1 on 2020-11-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_auto_20201130_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='mental_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
