# Generated by Django 3.1.1 on 2020-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_auto_20201130_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuicideRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('suicides_no', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('suicides_100kpo', models.FloatField(blank=True, null=True)),
                ('country_year', models.CharField(blank=True, max_length=50, null=True)),
                ('HDI_year', models.FloatField(blank=True, null=True)),
                ('gdp_year', models.IntegerField(blank=True, null=True)),
                ('gdp_per_capital', models.IntegerField(blank=True, null=True)),
                ('generation', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'suicide_rate',
                'get_latest_by': 'created',
            },
        ),
    ]
