# Generated by Django 3.1.1 on 2020-12-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_suiciderate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('current_education_status', models.IntegerField(blank=True, null=True)),
                ('occupation', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('live_with', models.IntegerField(blank=True, null=True)),
                ('plan_preg', models.IntegerField(blank=True, null=True)),
                ('who_support', models.IntegerField(blank=True, null=True)),
                ('ds1', models.IntegerField(blank=True, null=True)),
                ('ds2', models.IntegerField(blank=True, null=True)),
                ('ds3', models.IntegerField(blank=True, null=True)),
                ('ds4', models.IntegerField(blank=True, null=True)),
                ('ds5', models.IntegerField(blank=True, null=True)),
                ('ds6', models.IntegerField(blank=True, null=True)),
                ('ds7', models.IntegerField(blank=True, null=True)),
                ('ds8', models.IntegerField(blank=True, null=True)),
                ('ds9', models.IntegerField(blank=True, null=True)),
                ('ds10', models.IntegerField(blank=True, null=True)),
                ('total_ds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'depression',
                'get_latest_by': 'created',
            },
        ),
    ]
