# Generated by Django 3.1.1 on 2020-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0003_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='complete',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
