# Generated by Django 3.1.1 on 2020-11-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthtracker', '0007_goal_person_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='person_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
