# Generated by Django 3.1.1 on 2020-11-27 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthtracker', '0008_auto_20201127_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='person_of',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
