# Generated by Django 3.1.1 on 2020-11-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0009_auto_20201127_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='healthtracker.profile'),
        ),
    ]
