# Generated by Django 3.1.1 on 2020-11-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0010_goal_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='profile',
        ),
    ]
