# Generated by Django 3.1.1 on 2020-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0011_remove_goal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
