# Generated by Django 3.1.1 on 2020-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0012_auto_20201127_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
