# Generated by Django 3.1.1 on 2020-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtracker', '0016_auto_20201127_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='当ウェブサイトをご利用いただきありがとうございます。 登録プロセスが完了しました。', max_length=256),
        ),
    ]
