# Generated by Django 2.2.7 on 2020-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mental_info',
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'physical_info',
                'get_latest_by': 'created',
            },
        ),
    ]
