# Generated by Django 2.2.7 on 2020-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalinfo',
            name='general_information',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mentalinfo',
            name='prevention',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mentalinfo',
            name='symptoms',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mentalinfo',
            name='treatment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='physicalinfo',
            name='general_information',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='physicalinfo',
            name='prevention',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='physicalinfo',
            name='symptoms',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='physicalinfo',
            name='treatment',
            field=models.TextField(default=None),
        ),
    ]
