# Generated by Django 3.1.1 on 2020-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbook', '0005_auto_20201119_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=256, null=True)),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'contact',
                'get_latest_by': 'created',
            },
        ),
    ]
